<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner AppLocale="UTF16" ID="{178E6234-4974-4092-813A-33EE2567076E}" Label="" LastModificationDate="1385323631" Name="LogicalDataModel_1" Objects="4" Symbols="0" Type="{5F45F978-C4F3-4E35-A3FC-AF3318663A0F}" signature="LDM_DATA_MODEL_XML" version="16.7.0.6367"?>
<!-- do not edit this file -->

<Model xmlns:a="attribute" xmlns:c="collection" xmlns:o="object">

<o:RootObject Id="o1">
<c:Children>
<o:Model Id="o2">
<a:ObjectID>178E6234-4974-4092-813A-33EE2567076E</a:ObjectID>
<a:Name>LogicalDataModel_1</a:Name>
<a:Code>LOGICALDATAMODEL_1</a:Code>
<c:LogicalDiagrams>
<o:LogicalDiagram Id="o3">
<a:ObjectID>100606EF-AA82-4B59-B7CB-C6A286111A69</a:ObjectID>
<a:Name>Diagram 1</a:Name>
<a:Code>DIAGRAM_1</a:Code>
</o:LogicalDiagram>
</c:LogicalDiagrams>
<c:DefaultDiagram>
<o:LogicalDiagram Ref="o3"/>
</c:DefaultDiagram>
</o:Model>
</c:Children>
</o:RootObject>

</Model>